# Generated by Django 6.0 on 2025-12-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlystatement',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fecha límite de pago exacta', null=True),
        ),
        migrations.AlterField(
            model_name='monthlystatement',
            name='month_year',
            field=models.DateField(help_text='Mes al que corresponde este estado de cuenta'),
        ),
    ]
