# Generated by Django 6.0 on 2025-12-30 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_monthlystatement_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: iPhone 15 o Reestructura Enero', max_length=100)),
                ('type', models.CharField(choices=[('MSI', 'Meses sin Intereses'), ('FIXED', 'Pagos Fijos / Reestructura')], default='MSI', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_installments', models.IntegerField(help_text='Número total de meses')),
                ('current_installment', models.IntegerField(default=1, help_text='En qué mes vas actualmente')),
                ('monthly_payment', models.DecimalField(decimal_places=2, help_text='Monto a pagar cada mes', max_digits=12)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='cards.creditcard')),
            ],
        ),
    ]
