# Generated by Django 6.0 on 2025-12-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_installmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='color',
            field=models.CharField(default='#4f46e5', max_length=7),
        ),
    ]
