# Generated by Django 6.0 on 2026-01-03 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_creditcard_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlystatement',
            name='due_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Fecha límite de pago exacta'),
            preserve_default=False,
        ),
    ]
